/*
--================
-- Run in SQL PLUS
--================

Enter user-name: 
   
   sys/Sys_Admin1@localhost:1521/XEPDB1 AS SYSDBA 
   
*/
--------------------
--Run this in SQLPlus
--
--Create a few Roles
--------------------

SELECT ROLE FROM DBA_ROLES ORDER BY ROLE;


SQL> CREATE ROLE DB_DEMO_DEV;
SQL> CREATE ROLE DB_WEB_USER;
--CREATE ROLE DB_READWRITE;

--Role created.

--Add Grants to Role
SQL> @C:/oracle/DBMS_CRYPTO_DEMO/DB_DEMO_DEV_ROLE.sql
SQL> @C:/oracle/DBMS_CRYPTO_DEMO/WEB_USER_ROLE.sql

DROP USER DEMO;

-- CREATE USER DEMO
CREATE USER "DEMO" IDENTIFIED BY "DEMO2023"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

--User created.

-- QUOTAS
--ALTER USER "DEMO" QUOTA UNLIMITED ON "USERS";
ALTER USER "DEMO" QUOTA 10M ON "USERS";
ALTER USER "DEMO" QUOTA 5M ON "TEMP";

--User altered.

-- ROLES
--GRANT DBA TO "DEMO"
GRANT DB_DEMO_DEV TO "DEMO";

--Grant Execute on DBMS_CRYPTO Package to User
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO DEMO;

SELECT grantee, granted_role, admin_option
FROM dba_role_privs
WHERE grantee = 'DEMO';

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'DEMO';

SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTED_ROLE = 'DB_DEMO_DEV';

SELECT * FROM USER_TAB_PRIVS WHERE GRANTOR = 'DB_DEMO_DEV';

--Password expires after 30 Days
CREATE PROFILE MY_PROFILE LIMIT PASSWORD_LIFE_TIME 30;

--Password Reusage time - Unlimited
ALTER PROFILE MY_PROFILE LIMIT PASSWORD_REUSE_TIME UNLIMITED;

--Password Life Time - Never Expires
ALTER PROFILE MY_PROFILE LIMIT PASSWORD_LIFE_TIME UNLIMITED;

--Verify
SELECT * FROM DBA_PROFILES WHERE PROFILE = 'MY_PROFILE' AND RESOURCE_TYPE = 'PASSWORD';

ALTER USER DEMO PROFILE MY_PROFILE;

SELECT USERNAME, ACCOUNT_STATUS, EXPIRY_DATE FROM DBA_USERS WHERE USERNAME='DEMO';


--Run in SQLPlus:
-----------------------------------------------------------------------------------------------------

--This Anomynous Block will drop any existing Objects in the DEMO Schema
/*

BEGIN
  FOR cur_rec IN (SELECT object_name, object_type FROM dba_objects Where Owner = 'DEMO') LOOP
    BEGIN
      EXECUTE IMMEDIATE ' DROP ' || cur_rec.object_type || ' "DEMO"."' || cur_rec.object_name || '"';
      DBMS_OUTPUT.PUT_LINE('Dropped object: DEMO.' || cur_rec.object_name);
    EXCEPTION
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error dropping: ' || cur_rec.object_name || '. ' || SQLERRM);
    END;
  END LOOP;
END;
/
*/
--  Create new Objects in the DEMO Schema
--     @C:/oracle/DBMS_CRYPTO_DEMO/Oracle21cXE_DEMO_SCRIPTS.sql


/*
If you get an error like this after you compile your package for debugging and press the bug icon to run it:

ERROR:
Executing PL/SQL: CALL DBMS_DEBUG_JDWP.CONNECT_TCP( '127.0.0.1', '53125' )
ORA-24247: network access denied by access control list (ACL)
ORA-06512: at "SYS.DBMS_DEBUG_JDWP", line 68
ORA-06512: at line 1
Process exited.
Disconnecting from the database DEMO.

FIX:
 To allow User to run Package in DEBUG Mode run the following statement as SYS AS SYSDBA:
 

 BEGIN
  DBMS_NETWORK_ACL_ADMIN.APPEND_HOST_ACE(
    host => '127.0.0.1',
    lower_port => 1521,
    upper_port => NULL,
    ace => xs$ace_type(privilege_list => xs$name_list('JDWP'),
                        principal_name => 'DEMO',
                        -- principal_name => 'STORLTX',
                        principal_type => xs_acl.ptype_db));
END;



*/
/*  DO NOT RUN THIS!
PARAMETERS:
=================
Open up a CMD prompt and type in the following command:
-------------------------------------------------------
C:\Users\Tor>lsnrctl status

Output:
-----------

LSNRCTL for 64-bit Windows: Version 21.0.0.0.0 - Production on 28-DEC-2021 12:41:38

Copyright (c) 1991, 2021, Oracle.  All rights reserved.

Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=DESKTOP-156BLFL)(PORT=1521)))
STATUS of the LISTENER
------------------------
Alias                     LISTENER
Version                   TNSLSNR for 64-bit Windows: Version 21.0.0.0.0 - Production
Start Date                28-DEC-2021 10:45:13
Uptime                    0 days 1 hr. 56 min. 25 sec
Trace Level               off
Security                  ON: Local OS Authentication
SNMP                      OFF
Default Service           XE
Listener Parameter File   C:\app\Tor\product\21c\homes\OraDB21Home1\network\admin\listener.ora
Listener Log File         C:\app\Tor\product\21c\diag\tnslsnr\DESKTOP-156BLFL\listener\alert\log.xml
Listening Endpoints Summary...
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=DESKTOP-156BLFL)(PORT=1521)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(PIPENAME=\\.\pipe\EXTPROC1521ipc)))
  (DESCRIPTION=(ADDRESS=(PROTOCOL=tcps)(HOST=127.0.0.1)(PORT=5500))(Security=(my_wallet_directory=C:\APP\TOR\PRODUCT\21C\admin\XE\xdb_wallet))(Presentation=HTTP)(Session=RAW))
Services Summary...
Service "111eb2c0efab416aa869fa470d595f36" has 1 instance(s).
  Instance "xe", status READY, has 2 handler(s) for this service...
Service "CLRExtProc" has 1 instance(s).
  Instance "CLRExtProc", status UNKNOWN, has 1 handler(s) for this service...
Service "XE" has 1 instance(s).
  Instance "xe", status READY, has 2 handler(s) for this service...
Service "XEXDB" has 1 instance(s).
  Instance "xe", status READY, has 1 handler(s) for this service...
Service "xepdb1" has 1 instance(s).
  Instance "xe", status READY, has 2 handler(s) for this service...
The command completed successfully

**************************************************************/


/***********************************************
Run in Oracle21cXE as SYS/Sys_Admin1

CONNECTION STRINGS:
===================
SQL> sys/Sys_Admin1@localhost:1521/XEPDB1 AS SYSDBA;

/*
alter session set "_oracle_script"=true;

SELECT OBJECT_NAME, OBJECT_TYPE, ORACLE_MAINTAINED FROM DBA_OBJECTS 
WHERE ORACLE_MAINTAINED = 'Y'
--WHERE OBJECT_NAME='MY_PROFILE';
ORDER BY OBJECT_NAME;
*/





-- Selected Grants (These are Granted to the DB_DEMO_DEV Role in the file c:/oracle/DB_DEMO_DEV_ROLE.sql
-- Run this in SQL Plus logged in as SYSDBA:    @c:/oracle/DB_DEMO_DEV_ROLE.sql
-- Login to SQL Plus:   SQL> sys/Sys_Admin1@localhost:1521/XEPDB1 AS SYSDBA;
----------------------------------------------------------------------------------------------
--GRANT ADMINISTER ANY SQL TUNING SET TO "DEMO" ;
--GRANT ADMINISTER SQL TUNING SET TO "DEMO" ;
--GRANT ALTER ANY INDEX TO "DEMO" ;
--GRANT ALTER ANY INDEXTYPE TO "DEMO" ;
--GRANT ALTER ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT ALTER ANY PROCEDURE TO "DEMO" ;
--GRANT ALTER ANY ROLE TO "DEMO" ;
--GRANT ALTER ANY RULE SET TO "DEMO" ;
--GRANT ALTER ANY RULE TO "DEMO" ;
--GRANT ALTER ANY SEQUENCE TO "DEMO" ;
--GRANT ALTER ANY SQL PROFILE TO "DEMO" ;
--GRANT ALTER ANY TABLE TO "DEMO" ;
--GRANT ALTER ANY TRIGGER TO "DEMO" ;
--GRANT ALTER ANY TYPE TO "DEMO" ;
--GRANT ALTER DATABASE LINK TO "DEMO" ;
--GRANT ALTER PROFILE TO "DEMO" ;
--GRANT ALTER PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT ALTER SESSION TO "DEMO" ;
--GRANT ALTER USER TO "DEMO" ;
--GRANT ANALYZE ANY DICTIONARY TO "DEMO" ;
--GRANT ANALYZE ANY TO "DEMO" ;
--GRANT AUDIT ANY TO "DEMO" ;
--GRANT BACKUP ANY TABLE TO "DEMO" ;
--GRANT COMMENT ANY TABLE TO "DEMO" ;
--GRANT CREATE ANALYTIC VIEW TO "DEMO" ;
--GRANT CREATE ANY ANALYTIC VIEW TO "DEMO" ;
--GRANT CREATE ANY CREDENTIAL TO "DEMO" ;
--GRANT CREATE ANY DIRECTORY TO "DEMO" ;
--GRANT CREATE ANY HIERARCHY TO "DEMO" ;
--GRANT CREATE ANY INDEX TO "DEMO" ;
--GRANT CREATE ANY INDEXTYPE TO "DEMO" ;
--GRANT CREATE ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT CREATE ANY PROCEDURE TO "DEMO" ;
--GRANT CREATE ANY RULE SET TO "DEMO" ;
--GRANT CREATE ANY RULE TO "DEMO" ;
--GRANT CREATE ANY SEQUENCE TO "DEMO" ;
--GRANT CREATE ANY SQL PROFILE TO "DEMO" ;
--GRANT CREATE ANY SYNONYM TO "DEMO" ;
--GRANT CREATE ANY TABLE TO "DEMO" ;
--GRANT CREATE ANY TRIGGER TO "DEMO" ;
--GRANT CREATE ANY TYPE TO "DEMO" ;
--GRANT CREATE ANY VIEW TO "DEMO" ;
--GRANT CREATE CREDENTIAL TO "DEMO" ;
--GRANT CREATE DATABASE LINK TO "DEMO" ;
--GRANT CREATE INDEXTYPE TO "DEMO" ;
--GRANT CREATE MATERIALIZED VIEW TO "DEMO" ;
--GRANT CREATE PROCEDURE TO "DEMO" ;
--GRANT CREATE PROFILE TO "DEMO" ;
--GRANT CREATE PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT CREATE PUBLIC SYNONYM TO "DEMO" ;
--GRANT CREATE ROLE TO "DEMO" ;
--GRANT CREATE RULE TO "DEMO" ;
--GRANT CREATE SEQUENCE TO "DEMO" ;
--GRANT CREATE SESSION TO "DEMO" ;
--GRANT CREATE TABLE TO "DEMO" ;
--GRANT CREATE TRIGGER TO "DEMO" ;
--GRANT CREATE TYPE TO "DEMO" ;
--GRANT CREATE VIEW TO "DEMO" ;
--GRANT DEBUG ANY PROCEDURE TO "DEMO" ;
--GRANT DEBUG CONNECT ANY TO "DEMO" ;
--GRANT DELETE ANY TABLE TO "DEMO" ;
--GRANT DROP ANY ANALYTIC VIEW TO "DEMO" ;
--GRANT DROP ANY DIRECTORY TO "DEMO" ;
--GRANT DROP ANY INDEX TO "DEMO" ;
--GRANT DROP ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT DROP ANY PROCEDURE TO "DEMO" ;
--GRANT DROP ANY ROLE TO "DEMO" ;
--GRANT DROP ANY RULE SET TO "DEMO" ;
--GRANT DROP ANY RULE TO "DEMO" ;
--GRANT DROP ANY SEQUENCE TO "DEMO" ;
--GRANT DROP ANY SYNONYM TO "DEMO" ;
--GRANT DROP ANY TABLE TO "DEMO" ;
--GRANT DROP ANY TRIGGER TO "DEMO" ;
--GRANT DROP ANY TYPE TO "DEMO" ;
--GRANT DROP PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT DROP PUBLIC SYNONYM TO "DEMO" ;
--GRANT ENABLE DIAGNOSTICS TO "DEMO" ;
--GRANT EXECUTE ANY INDEXTYPE TO "DEMO" ;
--GRANT EXECUTE ANY LIBRARY TO "DEMO" ;
--GRANT EXECUTE ANY PROCEDURE TO "DEMO" ;
--GRANT EXECUTE ANY PROGRAM TO "DEMO" ;
--GRANT EXECUTE ANY RULE SET TO "DEMO" ;
--GRANT EXECUTE ANY RULE TO "DEMO" ;
--GRANT EXECUTE ANY TYPE TO "DEMO" ;
--GRANT FLASHBACK ANY TABLE TO "DEMO" ;
--GRANT GRANT ANY OBJECT PRIVILEGE TO "DEMO" ;
--GRANT GRANT ANY ROLE TO "DEMO" ;
--GRANT INSERT ANY TABLE TO "DEMO" ;
--GRANT KEEP DATE TIME TO "DEMO" ;
--GRANT MERGE ANY VIEW TO "DEMO" ;
--GRANT ON COMMIT REFRESH TO "DEMO" ;
--GRANT QUERY REWRITE TO "DEMO" ;
--GRANT READ ANY ANALYTIC VIEW CACHE TO "DEMO" ;
--GRANT READ ANY TABLE TO "DEMO" ;
--GRANT SELECT ANY DICTIONARY TO "DEMO" ;
--GRANT SELECT ANY SEQUENCE TO "DEMO" ;
--GRANT SELECT ANY TABLE TO "DEMO" ;
--GRANT SELECT ANY TRANSACTION TO "DEMO" ;
--GRANT TEXT DATASTORE ACCESS TO "DEMO" ;
--GRANT TRANSLATE ANY SQL TO "DEMO" ;
--GRANT UPDATE ANY TABLE TO "DEMO" ;
--GRANT WRITE ANY ANALYTIC VIEW CACHE TO "DEMO" ;



-- SYSTEM PRIVILEGES
--GRANT CREATE JOB TO "DEMO" ;
--GRANT DROP ANY CONTEXT TO "DEMO" ;
--GRANT UPDATE ANY CUBE TO "DEMO" ;
--GRANT ALTER ANY ANALYTIC VIEW TO "DEMO" ;
--GRANT DROP ANY TRIGGER TO "DEMO" ;
--GRANT DROP ANY SQL TRANSLATION PROFILE TO "DEMO" ;
--GRANT MANAGE ANY FILE GROUP TO "DEMO" ;
--GRANT ALTER PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT MANAGE FILE GROUP TO "DEMO" ;
--GRANT ALTER ANY INDEX TO "DEMO" ;
--GRANT DROP ANY SEQUENCE TO "DEMO" ;
--GRANT ALTER PROFILE TO "DEMO" ;
--GRANT INHERIT ANY PRIVILEGES TO "DEMO" ;
--GRANT UNDER ANY TABLE TO "DEMO" ;
--GRANT KEEP SYSGUID TO "DEMO" ;
--GRANT CREATE ASSEMBLY TO "DEMO" ;
--GRANT DROP ANY LIBRARY TO "DEMO" ;
--GRANT ALTER ANY EDITION TO "DEMO" ;
--GRANT CREATE ROLE TO "DEMO" ;
--GRANT CREATE LIBRARY TO "DEMO" ;
--GRANT DROP ROLLBACK SEGMENT TO "DEMO" ;
--GRANT CREATE TRIGGER TO "DEMO" ;
--GRANT ALTER ANY PROCEDURE TO "DEMO" ;
--GRANT ADMINISTER DATABASE TRIGGER TO "DEMO" ;
--GRANT DROP ANY MEASURE FOLDER TO "DEMO" ;
--GRANT CREATE ANY PROCEDURE TO "DEMO" ;
--GRANT ALTER ANY OUTLINE TO "DEMO" ;
--GRANT CREATE ANY ANALYTIC VIEW TO "DEMO" ;
--GRANT EXECUTE ANY INDEXTYPE TO "DEMO" ;
--GRANT USE ANY JOB RESOURCE TO "DEMO" ;
--GRANT CREATE ANY DIRECTORY TO "DEMO" ;
--GRANT ALTER ANY RULE SET TO "DEMO" ;
--GRANT USE ANY SQL TRANSLATION PROFILE TO "DEMO" ;
--GRANT ALTER ANY MINING MODEL TO "DEMO" ;
--GRANT DEBUG CONNECT SESSION TO "DEMO" ;
--GRANT LOGMINING TO "DEMO" ;
--GRANT DROP ANY ATTRIBUTE DIMENSION TO "DEMO" ;
--GRANT CREATE ANY MINING MODEL TO "DEMO" ;
--GRANT CREATE LOCKDOWN PROFILE TO "DEMO" ;
--GRANT ALTER SESSION TO "DEMO" ;
--GRANT CREATE MATERIALIZED VIEW TO "DEMO" ;
--GRANT CREATE PLUGGABLE DATABASE TO "DEMO" ;
--GRANT DROP ANY ANALYTIC VIEW TO "DEMO" ;
--GRANT WRITE ANY ANALYTIC VIEW CACHE TO "DEMO" ;
--GRANT MERGE ANY VIEW TO "DEMO" ;
--GRANT CREATE ANY INDEX TO "DEMO" ;
--GRANT READ ANY ANALYTIC VIEW CACHE TO "DEMO" ;
--GRANT CREATE DIMENSION TO "DEMO" ;
--GRANT EXECUTE ANY RULE SET TO "DEMO" ;
--GRANT CREATE SQL TRANSLATION PROFILE TO "DEMO" ;
--GRANT ALTER ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT AUDIT SYSTEM TO "DEMO" ;
--GRANT CREATE OPERATOR TO "DEMO" ;
--GRANT MANAGE ANY QUEUE TO "DEMO" ;
--GRANT ALTER ANY SQL PROFILE TO "DEMO" ;
--GRANT GRANT ANY OBJECT PRIVILEGE TO "DEMO" ;
--GRANT CREATE INDEXTYPE TO "DEMO" ;
--GRANT AUDIT ANY TO "DEMO" ;
--GRANT INHERIT ANY REMOTE PRIVILEGES TO "DEMO" ;
--GRANT SYSKM TO "DEMO" ;
--GRANT DEBUG ANY PROCEDURE TO "DEMO" ;
--GRANT CREATE ANY MEASURE FOLDER TO "DEMO" ;
--GRANT CREATE ANY SEQUENCE TO "DEMO" ;
--GRANT CREATE MEASURE FOLDER TO "DEMO" ;
--GRANT UPDATE ANY CUBE BUILD PROCESS TO "DEMO" ;
--GRANT CREATE VIEW TO "DEMO" ;
--GRANT ALTER DATABASE LINK TO "DEMO" ;
--GRANT ALTER ANY ASSEMBLY TO "DEMO" ;
--GRANT ALTER ANY SQL TRANSLATION PROFILE TO "DEMO" ;
--GRANT CREATE ANY EVALUATION CONTEXT TO "DEMO" ;
--GRANT SELECT ANY MINING MODEL TO "DEMO" ;
--GRANT SYSRAC TO "DEMO" ;
--GRANT DELETE ANY CUBE DIMENSION TO "DEMO" ;
--GRANT ALTER ANY TABLE TO "DEMO" ;
--GRANT ALTER ANY ATTRIBUTE DIMENSION TO "DEMO" ;
--GRANT CREATE SESSION TO "DEMO" ;
--GRANT CREATE RULE TO "DEMO" ;
--GRANT BECOME USER TO "DEMO" ;
--GRANT SELECT ANY CUBE BUILD PROCESS TO "DEMO" ;
--GRANT SELECT ANY TABLE TO "DEMO" ;
--GRANT INSERT ANY MEASURE FOLDER TO "DEMO" ;
--GRANT CREATE ANY SQL PROFILE TO "DEMO" ;
--GRANT FORCE ANY TRANSACTION TO "DEMO" ;
--GRANT DELETE ANY TABLE TO "DEMO" ;
--GRANT ALTER ANY SEQUENCE TO "DEMO" ;
--GRANT SELECT ANY CUBE DIMENSION TO "DEMO" ;
--GRANT CREATE ANY EDITION TO "DEMO" ;
--GRANT CREATE EXTERNAL JOB TO "DEMO" ;
--GRANT EM EXPRESS CONNECT TO "DEMO" ;
--GRANT DROP ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT CREATE ANY CUBE BUILD PROCESS TO "DEMO" ;
--GRANT FLASHBACK ANY TABLE TO "DEMO" ;
--GRANT DROP ANY RULE SET TO "DEMO" ;
--GRANT BACKUP ANY TABLE TO "DEMO" ;
--GRANT ALTER ANY CUBE TO "DEMO" ;
--GRANT CREATE CREDENTIAL TO "DEMO" ;
--GRANT CREATE TABLE TO "DEMO" ;
--GRANT EXECUTE ANY LIBRARY TO "DEMO" ;
--GRANT DROP ANY OUTLINE TO "DEMO" ;
--GRANT EXECUTE ASSEMBLY TO "DEMO" ;
--GRANT CREATE ANY HIERARCHY TO "DEMO" ;
--GRANT CREATE ANALYTIC VIEW TO "DEMO" ;
--GRANT CREATE ANY DIMENSION TO "DEMO" ;
--GRANT DROP ANY TABLE TO "DEMO" ;
--GRANT ADMINISTER KEY MANAGEMENT TO "DEMO" ;
--GRANT ALTER ANY CLUSTER TO "DEMO" ;
--GRANT EXECUTE ANY CLASS TO "DEMO" ;
--GRANT ALTER ANY CUBE BUILD PROCESS TO "DEMO" ;
--GRANT CREATE ANY CREDENTIAL TO "DEMO" ;
--GRANT DROP ANY DIMENSION TO "DEMO" ;
--GRANT SYSBACKUP TO "DEMO" ;
--GRANT CREATE ANY RULE SET TO "DEMO" ;
--GRANT SELECT ANY SEQUENCE TO "DEMO" ;
--GRANT UNDER ANY TYPE TO "DEMO" ;
--GRANT MANAGE TABLESPACE TO "DEMO" ;
--GRANT DROP ANY OPERATOR TO "DEMO" ;
--GRANT CREATE ANY OPERATOR TO "DEMO" ;
--GRANT DROP ANY HIERARCHY TO "DEMO" ;
--GRANT EXEMPT IDENTITY POLICY TO "DEMO" ;
--GRANT CREATE TYPE TO "DEMO" ;
--GRANT CREATE TABLESPACE TO "DEMO" ;
--GRANT SELECT ANY TRANSACTION TO "DEMO" ;
--GRANT DELETE ANY MEASURE FOLDER TO "DEMO" ;
--GRANT CREATE ANY CUBE TO "DEMO" ;
--GRANT LOCK ANY TABLE TO "DEMO" ;
--GRANT CREATE EVALUATION CONTEXT TO "DEMO" ;
--GRANT DROP ANY TYPE TO "DEMO" ;
--GRANT ADVISOR TO "DEMO" ;
--GRANT CREATE PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT ANALYZE ANY TO "DEMO" ;
--GRANT CREATE ATTRIBUTE DIMENSION TO "DEMO" ;
--GRANT DROP ANY RULE TO "DEMO" ;
--GRANT INSERT ANY CUBE DIMENSION TO "DEMO" ;
--GRANT CREATE ROLLBACK SEGMENT TO "DEMO" ;
--GRANT CREATE ANY JOB TO "DEMO" ;
--GRANT ALTER USER TO "DEMO" ;
--GRANT QUERY REWRITE TO "DEMO" ;
--GRANT SELECT ANY DICTIONARY TO "DEMO" ;
--GRANT CREATE PUBLIC SYNONYM TO "DEMO" ;
--GRANT DROP LOGICAL PARTITION TRACKING TO "DEMO" ;
--GRANT GLOBAL QUERY REWRITE TO "DEMO" ;
--GRANT ALTER ANY CUBE DIMENSION TO "DEMO" ;
--GRANT CREATE ANY CUBE DIMENSION TO "DEMO" ;
--GRANT DROP ANY CLUSTER TO "DEMO" ;
--GRANT CREATE ANY RULE TO "DEMO" ;
--GRANT UPDATE ANY CUBE DIMENSION TO "DEMO" ;
--GRANT SYSDBA TO "DEMO" ;
--GRANT CREATE LOGICAL PARTITION TRACKING TO "DEMO" ;
--GRANT ADMINISTER RESOURCE MANAGER TO "DEMO" ;
--GRANT CREATE ANY SYNONYM TO "DEMO" ;
--GRANT DROP ANY SYNONYM TO "DEMO" ;
--GRANT DROP ANY MINING MODEL TO "DEMO" ;
--GRANT EXECUTE ANY PROCEDURE TO "DEMO" ;
--GRANT CREATE SYNONYM TO "DEMO" ;
--GRANT SET CONTAINER TO "DEMO" ;
--GRANT EXECUTE ANY PROGRAM TO "DEMO" ;
--GRANT EXEMPT REDACTION POLICY TO "DEMO" ;
--GRANT EXECUTE ANY TYPE TO "DEMO" ;
--GRANT ON COMMIT REFRESH TO "DEMO" ;
--GRANT DEBUG CONNECT ANY TO "DEMO" ;
--GRANT CREATE SEQUENCE TO "DEMO" ;
--GRANT CREATE HIERARCHY TO "DEMO" ;
--GRANT SELECT ANY MEASURE FOLDER TO "DEMO" ;
--GRANT COMMENT ANY MINING MODEL TO "DEMO" ;
--GRANT ADMINISTER SQL TUNING SET TO "DEMO" ;
--GRANT SYSOPER TO "DEMO" ;
--GRANT CREATE ANY INDEXTYPE TO "DEMO" ;
--GRANT KEEP DATE TIME TO "DEMO" ;
--GRANT DROP ANY INDEX TO "DEMO" ;
--GRANT RESTRICTED SESSION TO "DEMO" ;
--GRANT SYSDG TO "DEMO" ;
--GRANT DEQUEUE ANY QUEUE TO "DEMO" ;
--GRANT ENABLE DIAGNOSTICS TO "DEMO" ;
--GRANT ANALYZE ANY DICTIONARY TO "DEMO" ;
--GRANT ALTER ANY INDEXTYPE TO "DEMO" ;
--GRANT TRANSLATE ANY SQL TO "DEMO" ;
--GRANT ADMINISTER ANY SQL TUNING SET TO "DEMO" ;
--GRANT CREATE USER TO "DEMO" ;
--GRANT EXECUTE ANY OPERATOR TO "DEMO" ;
--GRANT CREATE CUBE BUILD PROCESS TO "DEMO" ;
--GRANT CREATE PROFILE TO "DEMO" ;
--GRANT ALTER ANY ROLE TO "DEMO" ;
--GRANT UPDATE ANY TABLE TO "DEMO" ;
--GRANT ALTER ANY LIBRARY TO "DEMO" ;
--GRANT DROP ANY VIEW TO "DEMO" ;
--GRANT CREATE ANY CLUSTER TO "DEMO" ;
--GRANT EXECUTE ANY RULE TO "DEMO" ;
--GRANT ALTER TABLESPACE TO "DEMO" ;
--GRANT UNDER ANY VIEW TO "DEMO" ;
--GRANT EXECUTE ANY ASSEMBLY TO "DEMO" ;
--GRANT GRANT ANY PRIVILEGE TO "DEMO" ;
--GRANT ALTER ANY TRIGGER TO "DEMO" ;
--GRANT CREATE ANY VIEW TO "DEMO" ;
--GRANT ALTER LOCKDOWN PROFILE TO "DEMO" ;
--GRANT EXPORT FULL DATABASE TO "DEMO" ;
--GRANT ALTER ANY MEASURE FOLDER TO "DEMO" ;
--GRANT ALTER ANY EVALUATION CONTEXT TO "DEMO" ;
--GRANT TEXT DATASTORE ACCESS TO "DEMO" ;
--GRANT FLASHBACK ARCHIVE ADMINISTER TO "DEMO" ;
--GRANT IMPORT FULL DATABASE TO "DEMO" ;
--GRANT CREATE ANY OUTLINE TO "DEMO" ;
--GRANT COMMENT ANY TABLE TO "DEMO" ;
--GRANT READ ANY TABLE TO "DEMO" ;
--GRANT CREATE DATABASE LINK TO "DEMO" ;
--GRANT DROP PUBLIC SYNONYM TO "DEMO" ;
--GRANT DROP USER TO "DEMO" ;
--GRANT CHANGE NOTIFICATION TO "DEMO" ;
--GRANT CREATE MINING MODEL TO "DEMO" ;
--GRANT INSERT ANY TABLE TO "DEMO" ;
--GRANT DROP LOCKDOWN PROFILE TO "DEMO" ;
--GRANT DROP PROFILE TO "DEMO" ;
--GRANT CREATE ANY MATERIALIZED VIEW TO "DEMO" ;
--GRANT CREATE RULE SET TO "DEMO" ;
--GRANT EXEMPT ACCESS POLICY TO "DEMO" ;
--GRANT MANAGE SCHEDULER TO "DEMO" ;
--GRANT READ ANY FILE GROUP TO "DEMO" ;
--GRANT FORCE TRANSACTION TO "DEMO" ;
--GRANT DROP ANY CUBE BUILD PROCESS TO "DEMO" ;
--GRANT ALTER ANY TYPE TO "DEMO" ;
--GRANT DROP ANY PROCEDURE TO "DEMO" ;
--GRANT CREATE ANY SQL TRANSLATION PROFILE TO "DEMO" ;
--GRANT DROP PUBLIC DATABASE LINK TO "DEMO" ;
--GRANT DROP ANY INDEXTYPE TO "DEMO" ;
--GRANT DROP ANY SQL PROFILE TO "DEMO" ;
--GRANT EXECUTE DYNAMIC MLE TO "DEMO" ;
--GRANT ALTER SYSTEM TO "DEMO" ;
--GRANT UNLIMITED TABLESPACE TO "DEMO" ;
--GRANT DROP ANY ROLE TO "DEMO" ;
--GRANT ALTER ANY DIMENSION TO "DEMO" ;
--GRANT DROP ANY CUBE DIMENSION TO "DEMO" ;
--GRANT DROP ANY CUBE TO "DEMO" ;
--GRANT CREATE ANY TRIGGER TO "DEMO" ;
--GRANT DROP ANY ASSEMBLY TO "DEMO" ;
--GRANT CREATE ANY TABLE TO "DEMO" ;
--GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "DEMO" ;
--GRANT DROP ANY DIRECTORY TO "DEMO" ;
--GRANT ENQUEUE ANY QUEUE TO "DEMO" ;
--GRANT DROP ANY EVALUATION CONTEXT TO "DEMO" ;
--GRANT CREATE ANY ASSEMBLY TO "DEMO" ;
--GRANT CREATE ANY TYPE TO "DEMO" ;
--GRANT REDEFINE ANY TABLE TO "DEMO" ;
--GRANT CREATE CLUSTER TO "DEMO" ;
--GRANT CREATE ANY CONTEXT TO "DEMO" ;
--GRANT EXECUTE ANY EVALUATION CONTEXT TO "DEMO" ;
--GRANT RESUMABLE TO "DEMO" ;
--GRANT CREATE ANY LIBRARY TO "DEMO" ;
--GRANT DROP ANY EDITION TO "DEMO" ;
--GRANT CREATE PROCEDURE TO "DEMO" ;
--GRANT ALTER DATABASE TO "DEMO" ;
--GRANT SELECT ANY CUBE TO "DEMO" ;
--GRANT GRANT ANY ROLE TO "DEMO" ;
--GRANT ALTER ANY RULE TO "DEMO" ;
--GRANT CREATE ANY ATTRIBUTE DIMENSION TO "DEMO" ;
--GRANT CREATE CUBE DIMENSION TO "DEMO" ;
--GRANT ALTER ANY OPERATOR TO "DEMO" ;
--GRANT CREATE CUBE TO "DEMO" ;
--GRANT ALTER RESOURCE COST TO "DEMO" ;
--GRANT ALTER ANY HIERARCHY TO "DEMO" ;
--GRANT DROP TABLESPACE TO "DEMO" ;
--GRANT ALTER ROLLBACK SEGMENT TO "DEMO" ;
--GRANT PURGE DBA_RECYCLEBIN TO "DEMO" ;

