GRANT CONNECT TO DB_WEB_USER ;
GRANT CREATE SESSION TO DB_WEB_USER;
GRANT SELECT ON DEMO.DEMO_USER_PROFILE TO DB_WEB_USER;
GRANT EXECUTE ON DEMO.DEMO_SECURITY_PKG TO DB_WEB_USER;
GRANT EXECUTE ON DEMO.WEB_USER_DATA_PKG TO DB_WEB_USER;